#!/usr/bin/env python3
"""genitems.py -- pickup positions, taken from the level design.

`src/items.inc` carried a "GENERATED -- do not edit" header naming no generator
at all: orphaned output, exactly as the spawn table was before genspawns.py
existed. Its positions were arbitrary and its types literally alternated
1,0,1,0 down the file.

The level files author real pickups -- shells behind the first fight, a medkit
past the door it will be needed for. The engine supports four items of two
types per level (0 = medkit, +25 health; 1 = shells, +15 ammo), so the authored
set is collapsed onto that: stim and medkit become medkits, shells and shellbox
become shell pickups, and armour, weapons, keys, barrels and torches -- which
the engine cannot represent -- are ignored.

Two of each type per level, chosen by farthest-point sampling seeded at the
player spawn: the first pick of each type is the authored placement farthest
from the start, the second maximises spread against everything already chosen.
Deep items reward exploring, and nothing lands on the doorstep. Deterministic,
so the build stays byte-reproducible.

Every authored pickup is already validated reachable by the level compiler, so
unlike the spawns there is no relocation pass.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src')
LEVELS = os.path.join(HERE, '..', 'levels')
INC = os.path.join(SRC, 'items.inc')
sys.path.insert(0, HERE)
import levels as L                                              # noqa: E402

NITEM = 4                                   # a key, where there is one,
                                            # takes one of the four slots: level 1
                                            # only authors four usable pickups
MEDKIT, SHELLS = 0, 1                       # engine types (game.asm check_items)
KEY_RED, KEY_BLUE, KEY_YELLOW = 2, 3, 4
TYPEMAP = {L.THING['stim']: MEDKIT, L.THING['medkit']: MEDKIT,
           L.THING['shells']: SHELLS, L.THING['shellbox']: SHELLS}
KEYMAP = {L.THING['key_red']: KEY_RED, L.THING['key_blue']: KEY_BLUE,
          L.THING['key_yellow']: KEY_YELLOW}


def player_spawn(level):
    if level == 0:
        return (4, 6)
    hdr = open(os.path.join(SRC, 'map%d.lev.bin' % (level + 1)), 'rb').read()
    return (hdr[4], hdr[5])


def d2(a, b):
    return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2


def pick(cands, anchors, n):
    """Farthest-point sampling: each pick maximises min distance to anchors."""
    out, pool = [], list(cands)
    while pool and len(out) < n:
        best = max(pool, key=lambda c: min(d2(c, a) for a in anchors + out))
        out.append(best)
        pool.remove(best)
    return out


levs = L.load([os.path.join(LEVELS, f) for f in sorted(os.listdir(LEVELS))
               if f.endswith('.lev')])

xs, ys, ts = [], [], []
for lvl in range(4):
    spawn = player_spawn(lvl)
    byty = {MEDKIT: [], SHELLS: []}
    for x, y, t, a in levs[lvl].things:
        if t in TYPEMAP and (x, y) != spawn:
            byty[TYPEMAP[t]].append((x, y))
    # A key is not a pickup you might get -- without it the level cannot be
    # finished -- so it is placed FIRST, at the position its designer chose,
    # and supplies fill whatever slots are left.
    keys = [((x, y), KEYMAP[t]) for x, y, t, a in levs[lvl].things
            if t in KEYMAP and (x, y) != spawn]
    nsup = NITEM - len(keys)
    meds = pick(byty[MEDKIT], [spawn], (nsup + 1) // 2)
    ammo = pick(byty[SHELLS], [spawn] + meds, nsup - len(meds))
    chosen = keys + [(c, MEDKIT) for c in meds] + [(c, SHELLS) for c in ammo]
    assert len(chosen) == NITEM, \
        'level %d authors only %d usable pickups' % (lvl, len(chosen))
    kn = {KEY_RED: 'red', KEY_BLUE: 'blue', KEY_YELLOW: 'yellow'}
    print('  %-22s medkits %-14s shells %-14s %s'
          % (levs[lvl].name, meds, ammo,
             ' '.join('%s KEY at %s' % (kn[t].upper(), c) for c, t in keys)))
    xs += [c[0][0] for c in chosen]
    ys += [c[0][1] for c in chosen]
    ts += [c[1] for c in chosen]

with open(INC, 'w') as fh:
    fh.write('; GENERATED by tools/genitems.py -- do not edit\n')
    fh.write('NITEM = %d\n' % NITEM)
    fh.write('\n        org $2B40               ; below the spawn tables\n')
    for tag, vals in (('ITMX', xs), ('ITMY', ys), ('ITMT', ts)):
        fh.write(tag + '\n')
        for lvl in range(4):
            fh.write('        dta ' + ','.join(str(v) for v in vals[lvl * NITEM:(lvl + 1) * NITEM]) + '\n')

print('items.inc: %d pickups, all from the level design' % len(xs))
