#!/usr/bin/env python3
"""genlevels.py — pack levels 2..4 as RLE.

Each level is two 1KB planes (solid + attribute). Uncompressed that is 6KB for
three levels, which does not fit; RLE'd it is under 1.7KB. The format is the
simplest thing a 30-byte 6502 decoder can read:

    $00              end of stream
    $01..$7F  n      n literal bytes follow
    $81..$FF  n,byte (n & $7F) copies of byte

Level 1 stays uncompressed and resident because it is the one that boots.
"""
import os

SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'levels.bin')
INC = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'levels.inc')

LEVELS = [1, 2, 3, 4]        # ALL of them, so a finished game can restart:
                             # level 1's map is otherwise gone once you descend


def rle(d):
    out = bytearray()
    i = 0
    while i < len(d):
        run = 1
        while i + run < len(d) and d[i + run] == d[i] and run < 127:
            run += 1
        if run >= 3:
            out += bytes((0x80 | run, d[i]))
            i += run
        else:
            j = i
            lit = bytearray()
            while j < len(d) and len(lit) < 127:
                r = 1
                while j + r < len(d) and d[j + r] == d[j] and r < 127:
                    r += 1
                if r >= 3:
                    break
                lit.append(d[j])
                j += 1
            out += bytes((len(lit),)) + bytes(lit)
            i = j
    out += b'\x00'
    return bytes(out)


def unrle(c):
    out = bytearray()
    i = 0
    while i < len(c):
        b = c[i]
        if b == 0:
            break
        if b & 0x80:
            out += bytes([c[i + 1]]) * (b & 0x7F)
            i += 2
        else:
            out += c[i + 1:i + 1 + b]
            i += 1 + b
    return bytes(out)


blob = bytearray()
entries = []
for n in LEVELS:
    solid = open(f'{SRC}/map{n}.bin', 'rb').read()
    attr = open(f'{SRC}/map{n}.attr.bin', 'rb').read()
    hdr = open(f'{SRC}/map{n}.lev.bin', 'rb').read()
    sx, sy, sa = hdr[4], hdr[5], hdr[6]
    name = hdr[16:32].decode('latin1').strip()
    cs, ca = rle(solid), rle(attr)
    assert unrle(cs) == solid and unrle(ca) == attr, f'roundtrip failed for level {n}'
    entries.append((len(blob), len(blob) + len(cs), sx, sy, sa, name))
    blob += cs + ca

open(OUT, 'wb').write(blob)
with open(INC, 'w') as fh:
    fh.write('; GENERATED by tools/genlevels.py -- do not edit\n')
    fh.write('NLEVELS = %d                    ; levels 1..%d, RLE packed\n' % (len(LEVELS), LEVELS[-1]))
    fh.write('LEVELS_LEN = %d\n' % len(blob))
    fh.write('\n        org $4800               ; between the display lists ($4000-$47FF)\n'
             'LEVELDATA               ; and the generated tables ($5000). It used to sit\n'
             '        ins \'levels.bin\'  ; at $2500, where its last 54 bytes were quietly\n'
             '                        ; replaced by the item table at $2B40 -- level 4\'s\n'
             '                        ; lighting was corrupt over a quarter of the map.\n')
    fh.write('\n        ert * > $5000, "the level blob has overrun the generated tables at $5000"\n'
             '\n        org $2C00-64            ; small tables just below ladder A\nLVSOL_LO\n        dta ' + ','.join('<(LEVELDATA+%d)' % e[0] for e in entries) + '\n')
    fh.write('LVSOL_HI\n        dta ' + ','.join('>(LEVELDATA+%d)' % e[0] for e in entries) + '\n')
    fh.write('LVATR_LO\n        dta ' + ','.join('<(LEVELDATA+%d)' % e[1] for e in entries) + '\n')
    fh.write('LVATR_HI\n        dta ' + ','.join('>(LEVELDATA+%d)' % e[1] for e in entries) + '\n')
    fh.write('LVSPX\n        dta ' + ','.join(str(e[2]) for e in entries) + '\n')
    fh.write('LVSPY\n        dta ' + ','.join(str(e[3]) for e in entries) + '\n')
    fh.write('LVANG\n        dta ' + ','.join(str(e[4]) for e in entries) + '\n')

print('levels.bin %d bytes' % len(blob))
for i, e in enumerate(entries):
    print('  level %d "%s" spawn (%d,%d) ang %d  solid+%d attr+%d' % (LEVELS[i], e[5], e[2], e[3], e[4], e[0], e[1]))
