#!/usr/bin/env python3
"""gentitle.py — the ABYSS wordmark as framebuffer spans.

Same (start, count, data...) row format as the weapon, so the same blitter
draws it. 80x96 buffer, mode 9: one byte = two 4-bit luminance pixels.
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'title.bin')
INC = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'title.inc')

W_PX = 80

# 5x7 block letters, drawn at 2x horizontally so they read at 80px wide.
FONT = {
    'A': ["01110", "11011", "11011", "11111", "11011", "11011", "11011"],
    'B': ["11110", "11011", "11011", "11110", "11011", "11011", "11110"],
    'Y': ["11011", "11011", "01110", "00100", "00100", "00100", "00100"],
    'S': ["01111", "11000", "11000", "01110", "00011", "00011", "11110"],
}

WORD = "ABYSS"
LETTER_W = 5
GAP = 1


def render_word(word, scale_x=2):
    rows = []
    for r in range(7):
        line = ""
        for ch in word:
            for c in FONT[ch][r]:
                line += c * scale_x
            line += "0" * (GAP * scale_x)
        rows.append(line)
    return rows


glyph = render_word(WORD)
gw = len(glyph[0])
x0 = (W_PX - gw) // 2

# The wordmark sits in the upper third; each glyph row is 4 buffer rows tall
# so it reads as monumental rather than as text.
ROWS = 96
ROW_SCALE = 4
TOP = 32                        # inside the red wall hue band (rows ~30-64)

canvas = [[None] * W_PX for _ in range(ROWS)]
for gr, line in enumerate(glyph):
    for sub in range(ROW_SCALE):
        y = TOP + gr * ROW_SCALE + sub
        if y >= ROWS:
            break
        for i, c in enumerate(line):
            if c == '1':
                x = x0 + i
                if 0 <= x < W_PX:
                    # vertical gradient inside the letters: hot at the top,
                    # sinking into the dark at the bottom -- it is a pit
                    t = gr / 6.0
                    canvas[y][x] = max(6, int(14 - 8 * t))

# a horizon rule under the wordmark
rule_y = TOP + 7 * ROW_SCALE + 3
for x in range(4, W_PX - 4):
    canvas[rule_y][x] = 7
    canvas[rule_y + 1][x] = 4
# and a shorter one above, so the wordmark sits between two rules
for x in range(4, W_PX - 4):
    canvas[TOP - 4][x] = 4
    canvas[TOP - 3][x] = 7

data = bytearray()
for y in range(ROWS):
    px = canvas[y]
    idx = [i for i, v in enumerate(px) if v is not None]
    if not idx:
        data += bytes((0, 0))
        continue
    lo, hi = min(idx), max(idx)
    b0, b1 = lo // 2, hi // 2
    data += bytes((b0, b1 - b0 + 1))
    for b in range(b0, b1 + 1):
        p0 = px[b * 2] or 0
        p1 = px[b * 2 + 1] or 0
        data += bytes(((p0 << 4) | p1,))

open(OUT, 'wb').write(data)
with open(INC, 'w') as fh:
    fh.write('; GENERATED by tools/gentitle.py -- do not edit\n')
    fh.write('TITLE_ROWS = %d\n' % ROWS)
    fh.write('TITLE_LEN  = %d\n' % len(data))
print('title.bin %d bytes' % len(data))
